apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ttsiid5ee-python 
  janus-idp.io/tekton: ttsiid5ee-python
  backstage.io/kubernetes-id: ttsiid5ee-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ttsiid5ee-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml